### ISSUE TITLE
Error while running cmake ..

### ISSUE THREAD

**Issue by amitpathania** [SignalHound/soapy-bb60#1]
I have followed the instructions given in documentation to install soapy-bb60 but while running cmake .., I am getting following errors:
`
~/Documents/soapy-bb60/SoapyBB60C/build$ cmake ..
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "SoapySDR"
  (requested version 0.4.0) with any of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
`

**Comment by amitpathania** [comment]
Issue still not resolved. Please help

`
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:36 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_UNAME
    NAMES: "uname"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 1
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /home/lenevo/.local/bin/uname
    /usr/local/sbin/uname
    /usr/local/bin/uname
    /usr/sbin/uname
    /usr/bin/uname
    /sbin/uname

  The item was found at

    /bin/uname

Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeUnixFindMake.cmake:5 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_MAKE_PROGRAM
    NAMES: "gmake"
           "make"
           "smake"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 1
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /home/lenevo/.local/bin/gmake
    /usr/local/sbin/gmake
    /usr/local/bin/gmake
    /usr/sbin/gmake
    /usr/bin/gmake
    /sbin/gmake
    /bin/gmake
    /usr/games/gmake
    /usr/local/games/gmake
    /snap/bin/gmake
    /home/lenevo/.dotnet/tools/gmake
    /home/lenevo/.local/bin/make
    /usr/local/sbin/make
    /usr/local/bin/make
    /usr/sbin/make

  The item was found at

    /usr/bin/make

Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeDetermineCompiler.cmake:70 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_CXX_COMPILER
    NAMES: "c++"
           "CC"
           "g++"
           "aCC"
           "cl"
           "bcc"
           "xlC"
           "icpx"
           "icx"
           "clang++"
    Documentation: CXX compiler
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 1
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /home/lenevo/.local/bin/c++
    /usr/local/sbin/c++
    /usr/local/bin/c++
    /usr/sbin/c++

  The item was found at

    /usr/bin/c++

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:64 (_cmake_find_compiler)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:301 (find_file):
  find_file called with the following settings:

    VAR: src_in
    NAMES: "CMakeCXXCompilerId.cpp.in"
    Documentation: Path to a file.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    NO_DEFAULT_PATH Enabled

  find_file considered the following locations:

  The item was found at

    /usr/share/cmake-3.23/Modules/CMakeCXXCompilerId.cpp.in

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:323 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:59 (__determine_compiler_id_test)
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:120 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:7 (project)


-- The CXX compiler identification is GNU 7.5.0
CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_AR
    NAMES: "ar"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/ar

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_RANLIB
    NAMES: "ranlib"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/ranlib

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_STRIP
    NAMES: "strip"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/strip

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_LINKER
    NAMES: "ld"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/ld

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_NM
    NAMES: "nm"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/nm

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_OBJDUMP
    NAMES: "objdump"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/objdump

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_OBJCOPY
    NAMES: "objcopy"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/objcopy

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_READELF
    NAMES: "readelf"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/readelf

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_DLLTOOL
    NAMES: "dlltool"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /usr/bin/dlltool
    /home/lenevo/.local/bin/dlltool
    /usr/local/sbin/dlltool
    /usr/local/bin/dlltool
    /usr/sbin/dlltool
    /sbin/dlltool
    /bin/dlltool
    /usr/games/dlltool
    /usr/local/games/dlltool
    /snap/bin/dlltool
    /home/lenevo/.dotnet/tools/dlltool

  The item was not found.

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/CMakeFindBinUtils.cmake:220 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_ADDR2LINE
    NAMES: "addr2line"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

  The item was found at

    /usr/bin/addr2line

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:196 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/Compiler/GNU-FindBinUtils.cmake:18 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_CXX_COMPILER_AR
    NAMES: "gcc-ar-7.5"
           "gcc-ar-7"
           "gcc-ar"
    Documentation: A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /usr/bin/gcc-ar-7.5
    /home/lenevo/.local/bin/gcc-ar-7.5
    /usr/local/sbin/gcc-ar-7.5
    /usr/local/bin/gcc-ar-7.5
    /usr/sbin/gcc-ar-7.5
    /sbin/gcc-ar-7.5
    /bin/gcc-ar-7.5
    /usr/games/gcc-ar-7.5
    /usr/local/games/gcc-ar-7.5
    /snap/bin/gcc-ar-7.5
    /home/lenevo/.dotnet/tools/gcc-ar-7.5

  The item was found at

    /usr/bin/gcc-ar-7

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:197 (include)
  CMakeLists.txt:7 (project)


CMake Debug Log at /usr/share/cmake-3.23/Modules/Compiler/GNU-FindBinUtils.cmake:29 (find_program):
  find_program called with the following settings:

    VAR: CMAKE_CXX_COMPILER_RANLIB
    NAMES: "gcc-ranlib-7.5"
           "gcc-ranlib-7"
           "gcc-ranlib"
    Documentation: A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 0
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 0
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1

  find_program considered the following locations:

    /usr/bin/gcc-ranlib-7.5
    /home/lenevo/.local/bin/gcc-ranlib-7.5
    /usr/local/sbin/gcc-ranlib-7.5
    /usr/local/bin/gcc-ranlib-7.5
    /usr/sbin/gcc-ranlib-7.5
    /sbin/gcc-ranlib-7.5
    /bin/gcc-ranlib-7.5
    /usr/games/gcc-ranlib-7.5
    /usr/local/games/gcc-ranlib-7.5
    /snap/bin/gcc-ranlib-7.5
    /home/lenevo/.dotnet/tools/gcc-ranlib-7.5

  The item was found at

    /usr/bin/gcc-ranlib-7

Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineCXXCompiler.cmake:197 (include)
  CMakeLists.txt:7 (project)


-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "SoapySDR"
  (requested version 0.4.0) with any of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.


CMake Debug Log at CMakeLists.txt:9 (find_package):
  <PackageName>_ROOT CMake variable [CMAKE_FIND_USE_PACKAGE_ROOT_PATH].

    none

  CMAKE_PREFIX_PATH variable [CMAKE_FIND_USE_CMAKE_PATH].

    none

  CMAKE_FRAMEWORK_PATH and CMAKE_APPBUNDLE_PATH variables
  [CMAKE_FIND_USE_CMAKE_PATH].

    none

  Env variable SoapySDR_DIR [CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH].

    none

  CMAKE_PREFIX_PATH env variable [CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH].

    none

  CMAKE_FRAMEWORK_PATH and CMAKE_APPBUNDLE_PATH env variables
  [CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH].

    none

  Paths specified by the find_package HINTS option.

    none

  Standard system environment variables
  [CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH].

    /home/lenevo/.local
    /usr/local
    /usr
    /
    /usr/games
    /usr/local/games
    /snap
    /home/lenevo/.dotnet/tools

  CMake User Package Registry [CMAKE_FIND_USE_PACKAGE_REGISTRY].

    none

  CMake variables defined in the Platform file
  [CMAKE_FIND_USE_CMAKE_SYSTEM_PATH].

    /usr/X11R6
    /usr/pkg
    /opt

  CMake System Package Registry
  [CMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY].

    none

  Paths specified by the find_package PATHS option.

    none

  find_package considered the following locations for SoapySDR's Config
  module:

    /home/lenevo/.local/SoapySDRConfig.cmake
    /home/lenevo/.local/soapysdr-config.cmake
    /usr/local/SoapySDRConfig.cmake
    /usr/local/soapysdr-config.cmake
    /usr/SoapySDRConfig.cmake
    /usr/soapysdr-config.cmake
    /usr/lib/x86_64-linux-gnu/SoapySDR/SoapySDRConfig.cmake
    /usr/lib/x86_64-linux-gnu/SoapySDR/soapysdr-config.cmake
    /SoapySDRConfig.cmake
    /soapysdr-config.cmake
    /usr/games/SoapySDRConfig.cmake
    /usr/games/soapysdr-config.cmake
    /usr/local/games/SoapySDRConfig.cmake
    /usr/local/games/soapysdr-config.cmake
    /snap/SoapySDRConfig.cmake
    /snap/soapysdr-config.cmake
    /snap/cmake/SoapySDRConfig.cmake
    /snap/cmake/soapysdr-config.cmake
    /opt/SoapySDRConfig.cmake
    /opt/soapysdr-config.cmake

  The file was not found.



-- Configuring incomplete, errors occurred!

`

**Comment by amitpathania** [comment]
Issue resolved

**Comment by yuval174** [comment]
hey sorry for writing in this old issue but i run into the same problem and i couldn't find how you solved it.
my output from cmake ..
 CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (LibBB60).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  FindLibBB60.cmake:5 (INCLUDE)
  CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libbb_api'
--   No package 'libbb_api' found
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (BB60C) does
  not match the name of the calling package (LibBB60).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  FindLibBB60.cmake:27 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find BB60C (missing: BB60C_LIBRARIES BB60C_INCLUDE_DIRS) 
-- Performing Test HAS_STD_CXX11
-- Performing Test HAS_STD_CXX11 - Success
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BB60C_LIBRARIES (ADVANCED)
    linked by target "bb60Support" in directory /home/dbc/soapy-bb60/SoapyBB60C

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.


thank you in advance for the attention
